export type MigrationIdMaps = {
  user: Map<number, number>;
  client: Map<number, number>;
  product: Map<number, number>;
  warehouse: Map<number, number>;
  cashDesk: Map<number, number>;
  order: Map<number, number>;
  payment: Map<number, number>;
  goodsReceipt: Map<number, number>;
  salesReturn: Map<number, number>;
  tradeDirection: Map<number, number>;
  kpiGroup: Map<number, number>;
  bonusRule: Map<number, number>;
  planApproverConfig: Map<number, number>;
  salesKpiPlan: Map<number, number>;
  productCategory: Map<number, number>;
  productBrand: Map<number, number>;
  productManufacturer: Map<number, number>;
  productSegment: Map<number, number>;
  productCatalogGroup: Map<number, number>;
  interchangeableGroup: Map<number, number>;
  supplier: Map<number, number>;
  territory: Map<number, number>;
  workSlot: Map<number, number>;
  role: Map<number, number>;
  permission: Map<number, number>;
  currencyExchangeRate: Map<number, number>;
  orderRestrictionRule: Map<number, number>;
  orderAutoConfirmRule: Map<number, number>;
  productPrice: Map<number, number>;
  productPriceSchedule: Map<number, number>;
  territoryUserLink: Map<number, number>;
  slotUserLink: Map<number, number>;
  slotAuditEntry: Map<number, number>;
  cashDeskUserLink: Map<number, number>;
  cashDeskShift: Map<number, number>;
  warehouseUserLink: Map<number, number>;
  warehouseBlock: Map<number, number>;
  userBranchLink: Map<number, number>;
  userPaymentMethodLink: Map<number, number>;
  userTradeDirectionLink: Map<number, number>;
  clientAgentAssignment: Map<number, number>;
  clientBalance: Map<number, number>;
  supplierPayment: Map<number, number>;
  warehouseCorrection: Map<number, number>;
  warehouseCorrectionLine: Map<number, number>;
  stockTake: Map<number, number>;
  stockTakeLine: Map<number, number>;
  clientBalanceMovement: Map<number, number>;
  clientOpeningBalanceEntry: Map<number, number>;
  paymentEditGrant: Map<number, number>;
  orderAutoConfirmSchedule: Map<number, number>;
  retailOutletStock: Map<number, number>;
  clientEquipment: Map<number, number>;
  clientMergeLog: Map<number, number>;
  clientSavedDuplicateGroup: Map<number, number>;
  agentConsignmentMonthStatus: Map<number, number>;
  agentRouteDay: Map<number, number>;
  tenantTask: Map<number, number>;
  inAppNotification: Map<number, number>;
  userActivityEvent: Map<number, number>;
  accessLog: Map<number, number>;
  stockUpload: Map<number, number>;
  reportBuilderSavedConfig: Map<number, number>;
};

export function emptyIdMaps(): MigrationIdMaps {
  return {
    user: new Map(),
    client: new Map(),
    product: new Map(),
    warehouse: new Map(),
    cashDesk: new Map(),
    order: new Map(),
    payment: new Map(),
    goodsReceipt: new Map(),
    salesReturn: new Map(),
    tradeDirection: new Map(),
    kpiGroup: new Map(),
    bonusRule: new Map(),
    planApproverConfig: new Map(),
    salesKpiPlan: new Map(),
    productCategory: new Map(),
    productBrand: new Map(),
    productManufacturer: new Map(),
    productSegment: new Map(),
    productCatalogGroup: new Map(),
    interchangeableGroup: new Map(),
    supplier: new Map(),
    territory: new Map(),
    workSlot: new Map(),
    role: new Map(),
    permission: new Map(),
    currencyExchangeRate: new Map(),
    orderRestrictionRule: new Map(),
    orderAutoConfirmRule: new Map(),
    productPrice: new Map(),
    productPriceSchedule: new Map(),
    territoryUserLink: new Map(),
    slotUserLink: new Map(),
    slotAuditEntry: new Map(),
    cashDeskUserLink: new Map(),
    cashDeskShift: new Map(),
    warehouseUserLink: new Map(),
    warehouseBlock: new Map(),
    userBranchLink: new Map(),
    userPaymentMethodLink: new Map(),
    userTradeDirectionLink: new Map(),
    clientAgentAssignment: new Map(),
    clientBalance: new Map(),
    supplierPayment: new Map(),
    warehouseCorrection: new Map(),
    warehouseCorrectionLine: new Map(),
    stockTake: new Map(),
    stockTakeLine: new Map(),
    clientBalanceMovement: new Map(),
    clientOpeningBalanceEntry: new Map(),
    paymentEditGrant: new Map(),
    orderAutoConfirmSchedule: new Map(),
    retailOutletStock: new Map(),
    clientEquipment: new Map(),
    clientMergeLog: new Map(),
    clientSavedDuplicateGroup: new Map(),
    agentConsignmentMonthStatus: new Map(),
    agentRouteDay: new Map(),
    tenantTask: new Map(),
    inAppNotification: new Map(),
    userActivityEvent: new Map(),
    accessLog: new Map(),
    stockUpload: new Map(),
    reportBuilderSavedConfig: new Map()
  };
}
