export type Lang = "uz" | "ru";

const uz = {
  welcome: "👋 <b>Assalomu alaykum!</b>\n\nBu bot orqali hisobingiz, buyurtmalaringiz va to‘lovlaringizni kuzatasiz.\n\nKim sifatida kirasiz?",
  iAmClient: "🏪 Men mijozman",
  iAmStaff: "👔 Men xodimman",
  back: "⬅️ Orqaga",
  home: "🏠 Bosh menyu",
  cancel: "✖️ Bekor qilish",
  confirm: "✅ Tasdiqlash",
  refresh: "🔄 Yangilash",
  yes: "✅ Ha",
  no: "✖️ Yo‘q",
  done: "✅ Tayyor",
  error: "⚠️ Xatolik yuz berdi. Birozdan keyin qayta urinib ko‘ring.",
  noAccess: "⛔ Bu bo‘limga ruxsat yo‘q.",
  empty: "Ma’lumot yo‘q.",
  loading: "⏳ Tayyorlanmoqda…",
  blocked: "⛔ Urinishlar soni oshib ketdi. {min} daqiqadan keyin qayta urinib ko‘ring.",
  // mijoz ulanishi
  askCode: "🔐 <b>Ulanish kodi</b>\n\nAgent yoki ofis bergan 8 belgili kodni yuboring.\nMasalan: <code>K7QF-M2XP</code>",
  codeBad: "❌ Kod noto‘g‘ri yoki muddati o‘tgan.",
  askOrder:
    "🧾 Mijoz: <b>{name}</b>\n\nTasdiqlash uchun sizga yetkazilgan <b>oxirgi nakladnoylardan birining raqamini</b> yuboring (90 kun ichida).",
  orderBad: "❌ Nakladnoy raqami mos kelmadi. Qolgan urinishlar: {left}.",
  askPhone: "📱 Oxirgi qadam: pastdagi tugma orqali <b>telefon raqamingizni</b> yuboring.",
  sharePhone: "📱 Raqamni yuborish",
  skipPhone: "Raqamsiz davom etish",
  phoneNotYours: "❌ Faqat o‘zingizning raqamingizni yuboring (tugma orqali).",
  linkedOk: "🎉",
  linkedOkText: "✅ <b>{name}</b> hisobiga ulandingiz!",
  linkedPending: "⏳ So‘rov yuborildi. Telefon raqami mos kelmadi — ofis tasdiqlagandan keyin ma’lumotlar ochiladi.",
  pendingWait: "⏳ Ulanish so‘rovingiz ko‘rib chiqilmoqda. Tasdiqlangach xabar beramiz.",
  staffCantBeClient: "⛔ Bu Telegram akkaunt xodimga ulangan. Xodim mijoz sifatida ulana olmaydi.",
  clientCantBeStaff: "⛔ Bu Telegram akkaunt mijozga ulangan. Avval mijozdan uzing.",
  tooManyLinks: "⛔ Ulanishlar soni chegaradan oshdi.",
  alreadyLinked: "ℹ️ Siz bu mijozga allaqachon ulangansiz.",
  // xodim ulanishi
  askLogin: "👔 <b>Xodim sifatida kirish</b>\n\nLoginingizni yuboring:",
  askPassword: "🔑 Parolni yuboring (xabar darhol o‘chiriladi):",
  askSmart: "🔢 Ish o‘rningiz <b>smart-kodini</b> yuboring:",
  loginBad: "❌ Login yoki parol noto‘g‘ri.",
  smartBad: "❌ Smart-kod mos kelmadi.",
  staffBoundOther: "⛔ Bu xodim boshqa Telegram akkauntga ulangan. Administratorga murojaat qiling.",
  staffOk: "✅ Xush kelibsiz, <b>{name}</b>!",
  // menyu
  menuClient: "🏪 <b>{name}</b>",
  balance: "💰 Balans",
  orders: "📦 Buyurtmalar",
  payments: "💳 To‘lovlar",
  act: "📄 Akt sverka",
  consignment: "🧾 Konsignatsiya",
  returns: "↩️ Vozvratlar",
  orderRequest: "🛒 Buyurtma so‘rovi",
  myAgent: "👤 Agentim",
  settings: "⚙️ Sozlamalar",
  switchClient: "🔀 Mijozni almashtirish",
  overdue: "⚠️ Muddati o‘tgan: {sum}",
  // xodim menyusi
  today: "📊 Bugun",
  kpi: "🎯 KPI va reja",
  team: "👥 Jamoa",
  deliveries: "🚚 Yetkazishlar",
  myConsignment: "🧾 Konsignatsiyam",
  sales: "📈 Savdo",
  debts: "💸 Qarzdorlik",
  cash: "🏦 Kassalar",
  stock: "📦 Ombor",
  tasks: "✅ Vazifalar",
  payroll: "💵 Oyligim",
  reports: "📑 Hisobotlar",
  // sozlamalar
  language: "🌐 Til: O‘zbekcha",
  notifications: "🔔 Bildirishnomalar",
  quietHours: "🌙 Tungi rejim (22:00–08:00): {state}",
  on: "yoqilgan",
  off: "o‘chirilgan",
  unlink: "🚪 Botdan uzilish",
  logout: "🚪 Chiqish",
  unlinkConfirm: "⚠️ Rostdan ham botdan uzilmoqchimisiz? Qayta ulanish uchun yangi kod kerak bo‘ladi.",
  unlinked: "👋 Uzildingiz. Qayta ulanish uchun /start bosing.",
  // davrlar
  pTm: "Shu oy",
  pPm: "O‘tgan oy",
  p30: "30 kun",
  p90: "90 kun",
  pTy: "Shu yil",
  pdf: "📄 PDF",
  xlsx: "📊 Excel",
  choosePeriod: "📅 Davrni tanlang:",
  orderRequestAsk: "🛒 Nimani buyurtma qilmoqchisiz? Mahsulot va miqdorni bitta xabarda yozing — agentingizga yuboriladi.",
  orderRequestSent: "✅ So‘rov agentga yuborildi.",
  noAgent: "Agent biriktirilmagan."
};

export type TextKey = keyof typeof uz;

const ru: Record<TextKey, string> = {
  welcome: "👋 <b>Здравствуйте!</b>\n\nЧерез этого бота вы можете следить за балансом, заказами и оплатами.\n\nКак вы входите?",
  iAmClient: "🏪 Я клиент",
  iAmStaff: "👔 Я сотрудник",
  back: "⬅️ Назад",
  home: "🏠 Главное меню",
  cancel: "✖️ Отмена",
  confirm: "✅ Подтвердить",
  refresh: "🔄 Обновить",
  yes: "✅ Да",
  no: "✖️ Нет",
  done: "✅ Готово",
  error: "⚠️ Произошла ошибка. Попробуйте позже.",
  noAccess: "⛔ Нет доступа к этому разделу.",
  empty: "Нет данных.",
  loading: "⏳ Подготовка…",
  blocked: "⛔ Слишком много попыток. Повторите через {min} мин.",
  askCode: "🔐 <b>Код подключения</b>\n\nОтправьте 8-значный код, выданный агентом или офисом.\nНапример: <code>K7QF-M2XP</code>",
  codeBad: "❌ Код неверный или истёк.",
  askOrder:
    "🧾 Клиент: <b>{name}</b>\n\nДля подтверждения отправьте <b>номер одной из последних накладных</b>, доставленных вам (за 90 дней).",
  orderBad: "❌ Номер накладной не совпал. Осталось попыток: {left}.",
  askPhone: "📱 Последний шаг: отправьте <b>свой номер телефона</b> кнопкой ниже.",
  sharePhone: "📱 Отправить номер",
  skipPhone: "Продолжить без номера",
  phoneNotYours: "❌ Отправьте только свой номер (через кнопку).",
  linkedOk: "🎉",
  linkedOkText: "✅ Вы подключены к <b>{name}</b>!",
  linkedPending: "⏳ Запрос отправлен. Номер не совпал — данные откроются после подтверждения офисом.",
  pendingWait: "⏳ Ваш запрос на подключение рассматривается. Сообщим после подтверждения.",
  staffCantBeClient: "⛔ Этот Telegram привязан к сотруднику. Сотрудник не может подключиться как клиент.",
  clientCantBeStaff: "⛔ Этот Telegram привязан к клиенту. Сначала отключитесь от клиента.",
  tooManyLinks: "⛔ Превышен лимит подключений.",
  alreadyLinked: "ℹ️ Вы уже подключены к этому клиенту.",
  askLogin: "👔 <b>Вход для сотрудника</b>\n\nОтправьте логин:",
  askPassword: "🔑 Отправьте пароль (сообщение будет сразу удалено):",
  askSmart: "🔢 Отправьте <b>смарт-код</b> вашего рабочего места:",
  loginBad: "❌ Неверный логин или пароль.",
  smartBad: "❌ Смарт-код не совпал.",
  staffBoundOther: "⛔ Сотрудник привязан к другому Telegram. Обратитесь к администратору.",
  staffOk: "✅ Добро пожаловать, <b>{name}</b>!",
  menuClient: "🏪 <b>{name}</b>",
  balance: "💰 Баланс",
  orders: "📦 Заказы",
  payments: "💳 Оплаты",
  act: "📄 Акт сверки",
  consignment: "🧾 Консигнация",
  returns: "↩️ Возвраты",
  orderRequest: "🛒 Заявка на заказ",
  myAgent: "👤 Мой агент",
  settings: "⚙️ Настройки",
  switchClient: "🔀 Сменить клиента",
  overdue: "⚠️ Просрочено: {sum}",
  today: "📊 Сегодня",
  kpi: "🎯 KPI и план",
  team: "👥 Команда",
  deliveries: "🚚 Доставки",
  myConsignment: "🧾 Моя консигнация",
  sales: "📈 Продажи",
  debts: "💸 Задолженность",
  cash: "🏦 Кассы",
  stock: "📦 Склад",
  tasks: "✅ Задачи",
  payroll: "💵 Моя зарплата",
  reports: "📑 Отчёты",
  language: "🌐 Язык: Русский",
  notifications: "🔔 Уведомления",
  quietHours: "🌙 Ночной режим (22:00–08:00): {state}",
  on: "вкл",
  off: "выкл",
  unlink: "🚪 Отключиться от бота",
  logout: "🚪 Выйти",
  unlinkConfirm: "⚠️ Точно отключиться от бота? Для повторного подключения нужен новый код.",
  unlinked: "👋 Вы отключены. Для повторного подключения нажмите /start.",
  pTm: "Этот месяц",
  pPm: "Прошлый месяц",
  p30: "30 дней",
  p90: "90 дней",
  pTy: "Этот год",
  pdf: "📄 PDF",
  xlsx: "📊 Excel",
  choosePeriod: "📅 Выберите период:",
  orderRequestAsk: "🛒 Что хотите заказать? Напишите товары и количество одним сообщением — оно уйдёт вашему агенту.",
  orderRequestSent: "✅ Заявка отправлена агенту.",
  noAgent: "Агент не назначен."
};

const DICT: Record<Lang, Record<TextKey, string>> = { uz, ru };

export function normLang(v: unknown): Lang {
  return v === "ru" ? "ru" : "uz";
}

export function t(lang: Lang, key: TextKey, vars?: Record<string, string | number>): string {
  let s = DICT[lang][key] ?? uz[key];
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  return s;
}

/** Ikki tilli inline matn: `L(lang, "uz", "ru")`. */
export function L(lang: Lang, uzText: string, ruText: string): string {
  return lang === "ru" ? ruText : uzText;
}
