export type ProductPackagingInput = {
  name: string;
  quantity?: number | null;
  width_cm?: number | string | null;
  height_cm?: number | string | null;
  length_cm?: number | string | null;
  is_main?: boolean;
  sort_order?: number | null;
};

export type CreateProductInput = {
  sku: string;
  name: string;
  unit?: string;
  barcode?: string | null;
  category_id?: number | null;
  is_active?: boolean;
  product_group_id?: number | null;
  brand_id?: number | null;
  manufacturer_id?: number | null;
  segment_id?: number | null;
  segment_ids?: number[];
  trade_direction_ids?: number[];
  image_url?: string | null;
  packagings?: ProductPackagingInput[];
  weight_kg?: number | string | null;
  volume_m3?: number | string | null;
  qty_per_block?: number | null;
  dimension_unit?: string | null;
  width_cm?: number | string | null;
  height_cm?: number | string | null;
  length_cm?: number | string | null;
  ikpu_code?: string | null;
  hs_code?: string | null;
  sell_code?: string | null;
  comment?: string | null;
  sort_order?: number | null;
  is_blocked?: boolean;
  is_equipment?: boolean;
};

export type UpdateProductInput = {
  sku?: string;
  name?: string;
  unit?: string;
  barcode?: string | null;
  category_id?: number | null;
  is_active?: boolean;
  product_group_id?: number | null;
  brand_id?: number | null;
  manufacturer_id?: number | null;
  segment_id?: number | null;
  weight_kg?: number | string | null;
  volume_m3?: number | string | null;
  qty_per_block?: number | null;
  dimension_unit?: string | null;
  width_cm?: number | string | null;
  height_cm?: number | string | null;
  length_cm?: number | string | null;
  ikpu_code?: string | null;
  hs_code?: string | null;
  sell_code?: string | null;
  comment?: string | null;
  sort_order?: number | null;
  is_blocked?: boolean;
  is_equipment?: boolean;
};
