/** Поля системы — порядок в модалке импорта клиентов (совпадает с таблицей). */
export const CLIENT_IMPORT_MAPPABLE_FIELDS: { key: string; label: string }[] = [
  { key: "client_db_id", label: "ИД / id (создание с заданным id или обновление)" },
  { key: "name", label: "Наименование (новый клиент — обязательно)" },
  { key: "legal_name", label: "Юридическое название" },
  { key: "client_code", label: "Код клиента (короткий)" },
  { key: "client_pinfl", label: "ПИНФЛ" },
  { key: "phone", label: "Телефон" },
  { key: "address", label: "Адрес" },
  { key: "landmark", label: "Ориентир" },
  { key: "inn", label: "ИНН / STIR" },
  { key: "category_name", label: "Категория клиента" },
  { key: "category_code", label: "Категория клиента (код)" },
  { key: "client_type_name", label: "Тип клиента" },
  { key: "client_type_code", label: "Тип клиента (код)" },
  { key: "client_format_name", label: "Формат" },
  { key: "client_format_code", label: "Формат (код)" },
  { key: "sales_channel_name", label: "Торговый канал" },
  { key: "sales_channel_code", label: "Торговый канал (код)" },
  { key: "region", label: "Область / регион" },
  { key: "district", label: "Район" },
  { key: "city", label: "Город" },
  { key: "city_code", label: "Город (код)" },
  { key: "neighborhood", label: "Махалля / квартал" },
  { key: "zone", label: "Зона" },
  { key: "street", label: "Улица" },
  { key: "house_number", label: "Дом" },
  { key: "apartment", label: "Квартира / офис" },
  { key: "credit_limit", label: "Кредитный лимит" },
  { key: "is_active", label: "Активность (да/нет)" },
  { key: "responsible_person", label: "Ответственное лицо" },
  { key: "pdl", label: "P-D-L" },
  { key: "logistics_service", label: "Логистика" },
  { key: "license_until", label: "Срок лицензии" },
  { key: "working_hours", label: "Часы работы" },
  { key: "gps_text", label: "Текст GPS" },
  { key: "latitude", label: "Широта" },
  { key: "longitude", label: "Долгота" },
  { key: "notes", label: "Примечание" },
  { key: "product_category_ref", label: "Категория товара (текст / код)" },
  { key: "contact1_firstName", label: "Контакт 1: имя" },
  { key: "contact1_lastName", label: "Контакт 1: фамилия" },
  { key: "contact1_phone", label: "Контакт 1: телефон" },
  { key: "contact2_firstName", label: "Контакт 2: имя" },
  { key: "contact2_lastName", label: "Контакт 2: фамилия" },
  { key: "contact2_phone", label: "Контакт 2: телефон" },
  { key: "import_agent_1", label: "Команда: Агент 1" },
  { key: "import_agent_1_days", label: "Команда: Агент 1 — дни (Пн…Вс или 1–7)" },
  { key: "import_expeditor_1", label: "Команда: Экспедитор 1" },
  { key: "import_agent_2", label: "Команда: Агент 2" },
  { key: "import_agent_2_days", label: "Команда: Агент 2 — дни" },
  { key: "import_expeditor_2", label: "Команда: Экспедитор 2" },
  { key: "import_agent_3", label: "Команда: Агент 3" },
  { key: "import_agent_3_days", label: "Команда: Агент 3 — дни" },
  { key: "import_expeditor_3", label: "Команда: Экспедитор 3" }
];
