/**
 * Operatsiya nomlari (RU) — SalesDoc «Доступ» terminologiyasi bo'yicha.
 * Kalit: `<module>.<section>.<action>`; ro'yxatda yo'q kalit uchun umumiy amal nomi ishlatiladi.
 */
export const PERMISSION_OP_LABEL_RU: Record<string, string> = {
  "dashboard.prodazhi.view": "Продажа",
  "dashboard.finansy.view": "Финанс",
  "dashboard.supervayzer.view": "Супервайзер",
  "dashboard.plan_fakt.view": "Мониторинг продаж и планов",

  "orders.sozdanie.create": "Создать заказ",
  "orders.vozvrat_polki.create": "Создать возврат с полки",
  "orders.vozvrat_po_zakazu.create": "Создать возврат с полки по заказу",
  "orders.obmen.create": "Создать обмен",
  "orders.zakaz.view": "Список и просмотр заказов, итог по заказу",
  "orders.zakaz.update": "Изменение заказа (состав, комментарий, бонус)",
  "orders.zakaz.copy": "Печать и загрузка накладных",
  "orders.zakaz.export": "Выгрузка заказов в Excel (список, выбранные, итог)",
  "orders.zakaz.assign": "Прикрепить / открепить доставщика",
  "orders.zakaz.history": "История заказа",
  "orders.otkazy.view": "Список отказов",
  "orders.otkazy.create": "Добавить отказ",
  "orders.otkazy.export": "Выгрузка отказов в Excel",
  "orders.avtomatizatsiya.view": "Список правил автоматизации",
  "orders.avtomatizatsiya.create": "Создать и дублировать правило",
  "orders.avtomatizatsiya.update": "Редактировать правило",
  "orders.avtomatizatsiya.delete": "Удалить правило",
  "orders.avtomatizatsiya.restore": "Восстановить удалённое правило",
  "orders.avtomatizatsiya.export": "Выгрузка правил в Excel",
  "orders.avtomatizatsiya.activate": "Активировать правило",
  "orders.avtomatizatsiya.deactivate": "Деактивировать правило",
  "orders.status_confirmed.status": "Изменить статус на «Подтверждён»",
  "orders.status_picking.status": "Изменить статус на «Комплектация»",
  "orders.status_delivering.status": "Изменить статус на «Отгружен»",
  "orders.status_delivered.status": "Изменить статус на «Доставлен»",
  "orders.status_returned.status": "Изменить статус на «Возврат»",
  "orders.status_cancelled.status": "Изменить статус на «Отменён»",
  "orders.status_revert.status": "Вернуть на предыдущий статус",
  "orders.status_reopen.status": "Восстановить отменённый заказ (в «Новый»)",
  "orders.status_date.update": "Изменить дату статуса (отгрузка, доставка, возврат)",
  "orders.drugie_operacii.update": "Изменить консигнацию заказа",

  "clients.klient.view": "Список клиентов и профиль клиента",
  "clients.klient.create": "Добавление клиента",
  "clients.klient.update": "Изменение карточки клиента",
  "clients.klient.import": "Импорт клиентов из Excel (добавление и обновление)",
  "clients.klient.copy": "Экспорт клиентов в Excel",
  "clients.klient.activate": "Активация клиента",
  "clients.klient.deactivate": "Деактивация клиента",
  "clients.klient.history": "Журнал изменений клиента",
  "clients.vizity.view": "Просмотр карты назначения визитов",
  "clients.vizity_agent.update": "Привязать агента к клиентам на карте",
  "clients.vizity_dni.update": "Назначить дни визитов на карте",
  "clients.vizity_ekspeditor.update": "Назначить экспедитора на карте",
  "clients.vizity_sklad.update": "Назначить склад на карте",
  "clients.vizity_kassa.update": "Назначить кассу на карте",
  "clients.obedinenie.view": "Поиск дубликатов и предпросмотр объединения",
  "clients.obedinenie.update": "Объединить клиентов",
  "clients.obedinenie.create": "Сохранить группу дубликатов",
  "clients.obedinenie.delete": "Удалить сохранённую группу дубликатов",
  "clients.obedinenie.restore": "Восстановить удалённую группу дубликатов",
  "clients.obedinenie.history": "История объединений",
  "clients.oborudovanie.view": "Список оборудования и история",
  "clients.oborudovanie.create": "Выдать (добавить) оборудование клиенту",
  "clients.oborudovanie.delete": "Изъять оборудование у клиента",
  "clients.foto.view": "Просмотр фотоотчётов (включая архив)",
  "clients.foto.create": "Добавить фотоотчёт",
  "clients.foto.void": "Перенести фотоотчёт в архив",
  "clients.foto.restore": "Вернуть фотоотчёт из архива",
  "clients.ostatki_tt.view": "Просмотр остатков в торговых точках",
  "clients.ostatki_tt.import": "Загрузка остатков из Excel",
  "clients.ostatki_tt.copy": "Выгрузка остатков в Excel",

  "invoices.sborochnye.view": "Сборочные накладные — Список",
  "invoices.otgruzochnye.view": "Отгрузочные накладные — Список",
  "invoices.vozvratnye.view": "Возвратные накладные — Список",
  "invoices.vozvratnye.approve": "Подтвердить приёмку возврата",

  "cash.oplaty_klientov.view": "Список оплаты клиента",
  "cash.oplaty_klientov.create": "Создать оплаты клиента",
  "cash.oplaty_klientov.update": "Изменить оплату клиента (сумма, распределение, разрешение на изменение)",
  "cash.oplaty_klientov.approve": "Подтвердить / отклонить оплату клиента (вернуть экспедитору)",
  "cash.oplaty_klientov.export": "Выгрузка оплат клиентов в Excel",
  "cash.oplaty_klientov.delete": "Удалить оплаты клиента",
  "cash.oplaty_klientov.history": "Просмотр история оплаты клиента",
  "cash.perechisleniya.view": "Банковские платежи — Список",
  "cash.perechisleniya.create": "Платеж в банке — Создать",
  "cash.perechisleniya.update": "Банковские платежи — Распределение",
  "cash.perechisleniya.import": "Банковские платежи — обновление (импорт)",
  "cash.rashody_klienta.view": "Список расходы клиента",
  "cash.rashody_klienta.create": "Создать расходы клиента",
  "cash.rashody_klienta.update": "Изменить расходы клиента",
  "cash.rashody_klienta.delete": "Удалить расходы клиента",
  "cash.nachalnye_balansy.view": "Список начальные балансы",
  "cash.nachalnye_balansy.create": "Создать начальные балансы",
  "cash.nachalnye_balansy.update": "Изменение начальные остатки",
  "cash.nachalnye_balansy.void": "Аннулировать начальный баланс",
  "cash.nachalnye_balansy.restore": "Восстановить начальный баланс",
  "cash.balansy_klientov.view": "Список и деталь балансы клиентов",
  "cash.otchety.view": "Отчёты кассы (приходы, движение денежных средств, акты сверки)",
  "cash.kassa.view": "Список кассы",
  "cash.kassa.create": "Создать кассу",
  "cash.kassa.update": "Изменить кассу",
  "cash.kassa.status": "Открыть / закрыть смену кассы",
  "cash.kassa.export": "Выгрузка касс в Excel",
  "cash.kassa.history": "История кассы",
  "cash.kurs_valyuty.view": "Список курсов валют",
  "cash.kurs_valyuty.create": "Добавить курс валюты",
  "cash.kurs_valyuty.update": "Изменить курс валюты",
  "cash.prihody.view": "Список приходы",
  "cash.zayavki_na_oplatu.view": "Список заявки на оплату",
  "cash.zayavki_na_oplatu.approve": "Одобрить / отклонить заявки на оплату",
  "cash.dolgi_ekspeditora.view": "Список долги экспедитора",

  "warehouse.sklady.view": "Список складов",
  "warehouse.sklady.create": "Создать склада",
  "warehouse.sklady.update": "Изменить склада",
  "warehouse.sklady.delete": "Деактивировать / удалить склада",
  "warehouse.sklady.history": "История склада",
  "warehouse.bloki.view": "Список блоков склада",
  "warehouse.bloki.create": "Создать блок склада",
  "warehouse.bloki.update": "Изменить блок склада",
  "warehouse.bloki.delete": "Удалить блок склада",
  "warehouse.postuplenie.view": "Список товарных поступлении",
  "warehouse.postuplenie.create": "Создать товарных поступления",
  "warehouse.postuplenie.update": "Изменить товарных поступления",
  "warehouse.postuplenie.delete": "Удалить товарных поступления",
  "warehouse.postuplenie.import": "Импортировать с excel товарных поступлении",
  "warehouse.postuplenie.status": "Одобрить / отменить товарных поступления",
  "warehouse.postuplenie.history": "История товарных поступлений",
  "warehouse.peremeshchenie.view": "Движение (список перемещений)",
  "warehouse.peremeshchenie.create": "Создать перемещение",
  "warehouse.peremeshchenie.update": "Изменить перемещение",
  "warehouse.peremeshchenie.transfer": "Провести перемещение",
  "warehouse.korrektirovka.view": "Список корректировка и инвентаризация",
  "warehouse.korrektirovka.create": "Создать корректировку / инвентаризацию",
  "warehouse.korrektirovka.update": "Изменить корректировку / инвентаризацию",
  "warehouse.ostatki.view": "Остатки товаров",
  "warehouse.ostatki.copy": "Остатки товаров — Экспорт",
  "warehouse.rekomendovannyy_zapas.view": "Остатки товара на складе (рекомендованный запас)",
  "warehouse.ostatki_na_datu.view": "Остатки на определенную дату",
  "warehouse.ostatki_na_datu.copy": "Остатки на определенную дату — Экспорт",
  "warehouse.materialnyy_otchet.view": "Материальный отчет",

  "suppliers.postavshchik.view": "Список поставщиков",
  "suppliers.postavshchik.create": "Создание поставщиков",
  "suppliers.postavshchik.update": "Изменение поставщиков",
  "suppliers.postavshchik.delete": "Удаление поставщиков",
  "suppliers.postavshchik.history": "История поставщика",
  "suppliers.oplaty.view": "Оплата поставщику - Список",
  "suppliers.oplaty.create": "Оплата поставщику - Создать",
  "suppliers.oplaty.update": "Оплата поставщику - Изменить",
  "suppliers.balansy.view": "Начальный баланс, акт сверки и обороты по поставщикам",

  "plans.nastroyka_utverzhdayushchih.view": "Список утверждающих",
  "plans.nastroyka_utverzhdayushchih.update": "Изменить и сохранить утверждающего",
  "plans.ustanovka_planov.view": "Список планов",
  "plans.ustanovka_planov.create": "Создать план",
  "plans.ustanovka_planov.update": "Сохранить и отправить на утверждение",
  "plans.ustanovka_planov.approve": "Подтвердить / вернуть для редактирования",

  "reports.otchety.view": "Отчеты (по агентам, товарам, клиентам, визитам и др.)",
  "reports.otchety.copy": "Отчеты — Экспорт",
  "reports.konstruktor.view": "Конструктор отчетов",
  "reports.konstruktor.create": "Создать отчёт в конструкторе",
  "reports.konstruktor.update": "Изменить отчёт в конструкторе",
  "reports.konstruktor.copy": "Конструктор отчетов — Экспорт",
  "reports.dnevnye_kpi_plany.view": "Дневные KPI планы",

  "staff.agent.view": "Список агентов",
  "staff.agent.create": "Добавить агента",
  "staff.agent.update": "Изменить агента",
  "staff.agent.delete": "Удалить агента",
  "staff.agent.activate": "Активирование агента",
  "staff.agent.deactivate": "Деактивирование агента",
  "staff.agent.history": "История агента",
  "staff.ekspeditor.view": "Список экспедиторов",
  "staff.ekspeditor.create": "Создать экспедитора",
  "staff.ekspeditor.update": "Изменить экспедитора",
  "staff.ekspeditor.activate": "Активировать экспедитора",
  "staff.ekspeditor.deactivate": "Деактивировать экспедитора",
  "staff.ekspeditor.history": "История экспедитора",
  "staff.supervayzer.view": "Список супервайзеров",
  "staff.supervayzer.create": "Создание супервайзера",
  "staff.supervayzer.update": "Изменение супервайзера",
  "staff.supervayzer.activate": "Активировать супервайзера",
  "staff.supervayzer.deactivate": "Деактивировать супервайзера",
  "staff.supervayzer.history": "История супервайзера",
  "staff.skladchik.view": "Список складчика",
  "staff.skladchik.create": "Создать складчик",
  "staff.skladchik.update": "Изменить складчик",
  "staff.skladchik.activate": "Активировать складчика",
  "staff.skladchik.deactivate": "Деактивировать складчика",
  "staff.skladchik.history": "История складчика",
  "staff.inkassator.view": "Список инкассаторов",
  "staff.inkassator.create": "Создать инкассатора",
  "staff.inkassator.update": "Изменить инкассатора",
  "staff.inkassator.activate": "Активировать инкассатора",
  "staff.inkassator.deactivate": "Деактивировать инкассатора",
  "staff.inkassator.history": "История инкассатора",
  "staff.auditor.view": "Список аудиторов",
  "staff.auditor.create": "Создать аудитора",
  "staff.auditor.update": "Изменить аудитора",
  "staff.auditor.activate": "Активировать аудитора",
  "staff.auditor.deactivate": "Деактивировать аудитора",
  "staff.auditor.history": "История аудитора",
  "staff.sotrudniki.view": "Список сотрудников",
  "staff.sotrudniki.create": "Создание сотрудника",
  "staff.sotrudniki.update": "Редактирование сотрудников",
  "staff.sotrudniki.activate": "Сотрудники - активация",
  "staff.sotrudniki.deactivate": "Сотрудники - деактивация",
  "staff.konsignatsiya.view": "Просмотр список консигнации и лимитов агента",
  "staff.konsignatsiya.create": "Добавление лимитов агента",
  "staff.konsignatsiya.update": "Изменение консигнации и лимитов агента",
  "staff.rabochie_dni.view": "Просмотр рабочих дней",
  "staff.tabel.view": "Список работников в табеле",
  "staff.tabel.create": "Добавить исключение рабочего дня",
  "staff.tabel.update": "Изменить рабочие дни работников в табеле",
  "staff.tabel.history": "История изменений табеля",
  "staff.tabel_normativ.view": "Норматив агентов — Просмотр",
  "staff.tabel_normativ.update": "Норматив агентов — Изменение",
  "staff.zadachi.view": "Список задач и уведомлений",
  "staff.zadachi.update": "Изменение задачи",

  "gps.gps.view": "GPS мониторинг",
  "gps.gps.update": "Изменение полевых данных и последовательности визитов",
  "routes.marshruty.view": "Маршруты",
  "routes.marshruty.update": "Изменение маршрутов",
  "routes.trek.view": "Трек",

  "settings.tovar.view": "Список товаров",
  "settings.tovar.create": "Создать товар",
  "settings.tovar.update": "Изменить товар и справочники",
  "settings.tovar.delete": "Удалить товар",
  "settings.tovar.import": "Импорт товаров из Excel",
  "settings.tovar.copy": "Экспорт каталога товаров",
  "settings.tovar.history": "История товара",
  "settings.tsena.view": "Список цен",
  "settings.tsena.create": "Добавить цены",
  "settings.tsena.update": "Изменить цены",
  "settings.tsena.import": "Импорт цен из Excel",
  "settings.tsena.history": "История цен",
  "settings.bonusy_i_skidki.view": "Список бонусов и скидок",
  "settings.bonusy_i_skidki.create": "Создать бонус / скидку",
  "settings.bonusy_i_skidki.update": "Изменить бонус / скидку",
  "settings.bonusy_i_skidki.delete": "Удалить бонус / скидку",
  "settings.bonusy_i_skidki.history": "История бонусов и скидок",
  "settings.territoriya.view": "Список территорий",
  "settings.territoriya.create": "Создать территорию",
  "settings.territoriya.update": "Изменить территорию",
  "settings.territoriya.delete": "Удалить территорию",
  "settings.napravlenie_torgovli.view": "Список направлений торговли",
  "settings.napravlenie_torgovli.create": "Создать направление торговли",
  "settings.napravlenie_torgovli.update": "Изменить направление торговли",
  "settings.napravlenie_torgovli.delete": "Удалить направление торговли",
  "settings.geo_granitsy.view": "Список гео-границ",
  "settings.geo_granitsy.create": "Создать гео-границу",
  "settings.geo_granitsy.update": "Изменить гео-границу",
  "settings.geo_granitsy.history": "История гео-границ",
  "settings.profil_kompanii.view": "Просмотр профиля компании",
  "settings.profil_kompanii.update": "Изменить профиль компании",
  "settings.mobile_app.view": "Просмотр настроек мобильного приложения",
  "settings.mobile_app.update": "Изменить версию мобильного приложения",
  "settings.document_edit_lock.view": "Просмотр периода редактирования",
  "settings.document_edit_lock.update": "Изменить период редактирования",
  "settings.system_migration.view": "Просмотр системной миграции",
  "settings.system_migration.update": "Запустить миграцию",
  "settings.system_migration.import": "Импорт данных миграции",

  "staff.zarplaty.view": "Список зарплат",
  "staff.zarplaty.create": "Создание расчёта зарплаты",
  "staff.zarplaty.update": "Зарплата — Изменить",
  "staff.zarplaty.delete": "Зарплата — Удалить",
  "staff.zarplaty.copy": "Зарплата — Экспорт",
  "staff.zarplaty.import": "Зарплата — Импорт",
  "staff.zarplaty.assign": "Прикрепить бонусы и формулы",
  "staff.zarplaty.status": "Зарплата — Отправить / вернуть на доработку",
  "staff.zarplaty.approve": "Зарплата — Подтвердить",
  "staff.avans.view": "Список авансов",
  "staff.avans.create": "Создать аванс",
  "staff.avans.update": "Изменить аванс",
  "staff.avans.delete": "Удалить аванс",
  "staff.avans.import": "Импорт авансов из Excel",
  "staff.avans.status": "Отправить / отменить аванс",
  "staff.avans_limity.view": "Просмотр лимитов аванса",
  "staff.avans_limity.update": "Изменить лимиты аванса",
  "finance.avans.view": "Список авансов на утверждение",
  "finance.avans.approve": "Утвердить / отклонить аванс",
  "cash.vydacha_zarplaty.view": "Список выплаченных зарплат",
  "cash.vydacha_zarplaty.create": "Создание платежа зарплаты",
  "cash.vydacha_zarplaty.void": "Отменить выплату зарплаты",
  "cash.vydacha_zarplaty.history": "История выплат зарплаты",

  "work_slots.raboche_mesto.view": "Список рабочих мест",
  "work_slots.raboche_mesto.create": "Создать рабочее место",
  "work_slots.raboche_mesto.update": "Изменить рабочее место",
  "work_slots.raboche_mesto.assign": "Прикрепить сотрудника к рабочему месту",
  "work_slots.raboche_mesto.history": "История рабочего места",

  "access.upravlenie.view": "Просмотр раздела «Доступ»",
  "access.upravlenie.update": "Изменение доступов пользователей и ролей",
  "access.upravlenie.history": "Список истории предоставленного доступа",
  "access.upravlenie.export": "Выгрузка истории доступа в Excel",

  "dashboard.prodazhi.export": "Продажа — выгрузка в Excel",
  "dashboard.finansy.export": "Финанс — выгрузка в Excel",
  "dashboard.supervayzer.export": "Супервайзер — выгрузка в Excel",
  "clients.oborudovanie.export": "Выгрузка оборудования в Excel",
  "cash.balansy_klientov.export": "Выгрузка балансов клиентов в Excel",
  "cash.otchety.export": "Выгрузка отчётов кассы в Excel (приходы, ДДС, акты сверки, долги)",
  "cash.kurs_valyuty.export": "Выгрузка курсов валют в Excel",
  "cash.zayavki_na_oplatu.export": "Выгрузка заявок на оплату в Excel",
  "warehouse.sklady.export": "Выгрузка складов в Excel",
  "warehouse.bloki.export": "Выгрузка блоков склада в Excel",
  "warehouse.postuplenie.export": "Выгрузка поступлений и отчёта поступлений в Excel",
  "warehouse.peremeshchenie.export": "Выгрузка перемещений в Excel",
  "warehouse.korrektirovka.export": "Выгрузка корректировок в Excel",
  "warehouse.rekomendovannyy_zapas.export": "Рекомендованный запас — выгрузка в Excel",
  "warehouse.materialnyy_otchet.export": "Материальный отчет — выгрузка в Excel",
  "suppliers.postavshchik.export": "Выгрузка поставщиков в Excel",
  "suppliers.oplaty.export": "Выгрузка оплат поставщикам в Excel",
  "suppliers.balansy.export": "Выгрузка балансов и акта сверки в Excel",
  "reports.dnevnye_kpi_plany.export": "Дневные KPI планы — выгрузка в Excel",
  "staff.agent.export": "Выгрузка агентов в Excel",
  "staff.ekspeditor.export": "Выгрузка экспедиторов в Excel",
  "staff.supervayzer.export": "Выгрузка супервайзеров в Excel",
  "staff.skladchik.export": "Выгрузка складчиков в Excel",
  "staff.inkassator.export": "Выгрузка инкассаторов в Excel",
  "staff.auditor.export": "Выгрузка аудиторов в Excel",
  "staff.sotrudniki.export": "Выгрузка сотрудников в Excel",
  "staff.konsignatsiya.export": "Выгрузка консигнации и лимитов в Excel",
  "staff.tabel.export": "Выгрузка табеля в Excel",
  "gps.gps.export": "Выгрузка GPS / визитов в Excel",
  "settings.bonusy_i_skidki.export": "Выгрузка бонусов и скидок в Excel",
  "settings.napravlenie_torgovli.export": "Выгрузка направлений торговли и KPI групп в Excel",
  "settings.kategoriya_tovara.view": "Категория товара",
  "settings.kategoriya_tovara.export": "Категория товара — выгрузка в Excel",
  "settings.kanal_sbyta.view": "Канал сбыта",
  "settings.kanal_sbyta.export": "Канал сбыта — выгрузка в Excel",
  "settings.orders_consignment.view": "Заказы → консигнация",
  "settings.orders_consignment.export": "Заказы → консигнация — выгрузка в Excel",
  "settings.initial_setup.view": "Начальная настройка",
  "settings.initial_setup.export": "Начальная настройка — выгрузка шаблона в Excel",
  "audit.log.view": "Журнал аудита",
  "audit.log.export": "Выгрузка журнала аудита в Excel",
  "work_slots.raboche_mesto.export": "Выгрузка рабочих мест в Excel",
  "diagnostics.error_logs.view": "Журнал ошибок",
  "diagnostics.error_logs.export": "Выгрузка журнала ошибок в Excel",
  "activity.history.view": "Активность и история",
  "activity.history.export": "Выгрузка активности в Excel"
};
